/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as FiyatlandirmaRouteImport } from './routes/fiyatlandirma'
import { Route as FreeAiReadinessReportRouteImport } from './routes/free-ai-readiness-report'
import { Route as HakkimizdaRouteImport } from './routes/hakkimizda'
import { Route as KvkkRouteImport } from './routes/kvkk'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as MakalelerRouteImport } from './routes/makaleler'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SunumRouteImport } from './routes/sunum'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as MakalelerIndexRouteImport } from './routes/makaleler.index'
import { Route as MakalelerSlugRouteImport } from './routes/makaleler.$slug'
import { Route as PlatformIndexRouteImport } from './routes/platform.index'
import { Route as PlatformCitationShareRouteImport } from './routes/platform.citation-share'
import { Route as PlatformEvidenceGapsRouteImport } from './routes/platform.evidence-gaps'
import { Route as ProofFilmfolkRouteImport } from './routes/proof.filmfolk'
import { Route as RTokenRouteImport } from './routes/r.$token'
import { Route as SolutionsAgenciesRouteImport } from './routes/solutions.agencies'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppAccountRouteImport } from './routes/_authenticated/app.account'
import { Route as AuthenticatedAppAdminRouteImport } from './routes/_authenticated/app.admin'
import { Route as AuthenticatedAppCitationDiscoveryRouteImport } from './routes/_authenticated/app.citation-discovery'
import { Route as AuthenticatedAppClaimsRouteImport } from './routes/_authenticated/app.claims'
import { Route as AuthenticatedAppContentRouteImport } from './routes/_authenticated/app.content'
import { Route as AuthenticatedAppGeoTasksRouteImport } from './routes/_authenticated/app.geo-tasks'
import { Route as AuthenticatedAppGraphRouteImport } from './routes/_authenticated/app.graph'
import { Route as AuthenticatedAppIntegrationsRouteImport } from './routes/_authenticated/app.integrations'
import { Route as AuthenticatedAppKnowledgeBaseRouteImport } from './routes/_authenticated/app.knowledge-base'
import { Route as AuthenticatedAppMeasurementRouteImport } from './routes/_authenticated/app.measurement'
import { Route as AuthenticatedAppOnboardingRouteImport } from './routes/_authenticated/app.onboarding'
import { Route as AuthenticatedAppPricingRouteImport } from './routes/_authenticated/app.pricing'
import { Route as AuthenticatedAppPromptDiscoveryRouteImport } from './routes/_authenticated/app.prompt-discovery'
import { Route as AuthenticatedAppPromptsRouteImport } from './routes/_authenticated/app.prompts'
import { Route as AuthenticatedAppReportRouteImport } from './routes/_authenticated/app.report'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app.settings'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const FiyatlandirmaRoute = FiyatlandirmaRouteImport.update({
  id: '/fiyatlandirma',
  path: '/fiyatlandirma',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeAiReadinessReportRoute = FreeAiReadinessReportRouteImport.update({
  id: '/free-ai-readiness-report',
  path: '/free-ai-readiness-report',
  getParentRoute: () => rootRouteImport,
} as any)
const HakkimizdaRoute = HakkimizdaRouteImport.update({
  id: '/hakkimizda',
  path: '/hakkimizda',
  getParentRoute: () => rootRouteImport,
} as any)
const KvkkRoute = KvkkRouteImport.update({
  id: '/kvkk',
  path: '/kvkk',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const MakalelerRoute = MakalelerRouteImport.update({
  id: '/makaleler',
  path: '/makaleler',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SunumRoute = SunumRouteImport.update({
  id: '/sunum',
  path: '/sunum',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const MakalelerIndexRoute = MakalelerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MakalelerRoute,
} as any)
const MakalelerSlugRoute = MakalelerSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MakalelerRoute,
} as any)
const PlatformIndexRoute = PlatformIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformCitationShareRoute = PlatformCitationShareRouteImport.update({
  id: '/citation-share',
  path: '/citation-share',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformEvidenceGapsRoute = PlatformEvidenceGapsRouteImport.update({
  id: '/evidence-gaps',
  path: '/evidence-gaps',
  getParentRoute: () => PlatformRoute,
} as any)
const ProofFilmfolkRoute = ProofFilmfolkRouteImport.update({
  id: '/proof/filmfolk',
  path: '/proof/filmfolk',
  getParentRoute: () => rootRouteImport,
} as any)
const RTokenRoute = RTokenRouteImport.update({
  id: '/r/$token',
  path: '/r/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsAgenciesRoute = SolutionsAgenciesRouteImport.update({
  id: '/solutions/agencies',
  path: '/solutions/agencies',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAccountRoute = AuthenticatedAppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAdminRoute = AuthenticatedAppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppCitationDiscoveryRoute =
  AuthenticatedAppCitationDiscoveryRouteImport.update({
    id: '/citation-discovery',
    path: '/citation-discovery',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppClaimsRoute = AuthenticatedAppClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppContentRoute = AuthenticatedAppContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppGeoTasksRoute =
  AuthenticatedAppGeoTasksRouteImport.update({
    id: '/geo-tasks',
    path: '/geo-tasks',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppGraphRoute = AuthenticatedAppGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppIntegrationsRoute =
  AuthenticatedAppIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppKnowledgeBaseRoute =
  AuthenticatedAppKnowledgeBaseRouteImport.update({
    id: '/knowledge-base',
    path: '/knowledge-base',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMeasurementRoute =
  AuthenticatedAppMeasurementRouteImport.update({
    id: '/measurement',
    path: '/measurement',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppOnboardingRoute =
  AuthenticatedAppOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPricingRoute = AuthenticatedAppPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPromptDiscoveryRoute =
  AuthenticatedAppPromptDiscoveryRouteImport.update({
    id: '/prompt-discovery',
    path: '/prompt-discovery',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPromptsRoute = AuthenticatedAppPromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppReportRoute = AuthenticatedAppReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/fiyatlandirma': typeof FiyatlandirmaRoute
  '/free-ai-readiness-report': typeof FreeAiReadinessReportRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/kvkk': typeof KvkkRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/makaleler': typeof MakalelerRouteWithChildren
  '/mcp': typeof McpRoute
  '/platform': typeof PlatformRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sunum': typeof SunumRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/makaleler/$slug': typeof MakalelerSlugRoute
  '/platform/citation-share': typeof PlatformCitationShareRoute
  '/platform/evidence-gaps': typeof PlatformEvidenceGapsRoute
  '/proof/filmfolk': typeof ProofFilmfolkRoute
  '/r/$token': typeof RTokenRoute
  '/solutions/agencies': typeof SolutionsAgenciesRoute
  '/makaleler/': typeof MakalelerIndexRoute
  '/platform/': typeof PlatformIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/app/account': typeof AuthenticatedAppAccountRoute
  '/app/admin': typeof AuthenticatedAppAdminRoute
  '/app/citation-discovery': typeof AuthenticatedAppCitationDiscoveryRoute
  '/app/claims': typeof AuthenticatedAppClaimsRoute
  '/app/content': typeof AuthenticatedAppContentRoute
  '/app/geo-tasks': typeof AuthenticatedAppGeoTasksRoute
  '/app/graph': typeof AuthenticatedAppGraphRoute
  '/app/integrations': typeof AuthenticatedAppIntegrationsRoute
  '/app/knowledge-base': typeof AuthenticatedAppKnowledgeBaseRoute
  '/app/measurement': typeof AuthenticatedAppMeasurementRoute
  '/app/onboarding': typeof AuthenticatedAppOnboardingRoute
  '/app/pricing': typeof AuthenticatedAppPricingRoute
  '/app/prompt-discovery': typeof AuthenticatedAppPromptDiscoveryRoute
  '/app/prompts': typeof AuthenticatedAppPromptsRoute
  '/app/report': typeof AuthenticatedAppReportRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/fiyatlandirma': typeof FiyatlandirmaRoute
  '/free-ai-readiness-report': typeof FreeAiReadinessReportRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/kvkk': typeof KvkkRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sunum': typeof SunumRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/makaleler/$slug': typeof MakalelerSlugRoute
  '/platform/citation-share': typeof PlatformCitationShareRoute
  '/platform/evidence-gaps': typeof PlatformEvidenceGapsRoute
  '/proof/filmfolk': typeof ProofFilmfolkRoute
  '/r/$token': typeof RTokenRoute
  '/solutions/agencies': typeof SolutionsAgenciesRoute
  '/makaleler': typeof MakalelerIndexRoute
  '/platform': typeof PlatformIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/app/account': typeof AuthenticatedAppAccountRoute
  '/app/admin': typeof AuthenticatedAppAdminRoute
  '/app/citation-discovery': typeof AuthenticatedAppCitationDiscoveryRoute
  '/app/claims': typeof AuthenticatedAppClaimsRoute
  '/app/content': typeof AuthenticatedAppContentRoute
  '/app/geo-tasks': typeof AuthenticatedAppGeoTasksRoute
  '/app/graph': typeof AuthenticatedAppGraphRoute
  '/app/integrations': typeof AuthenticatedAppIntegrationsRoute
  '/app/knowledge-base': typeof AuthenticatedAppKnowledgeBaseRoute
  '/app/measurement': typeof AuthenticatedAppMeasurementRoute
  '/app/onboarding': typeof AuthenticatedAppOnboardingRoute
  '/app/pricing': typeof AuthenticatedAppPricingRoute
  '/app/prompt-discovery': typeof AuthenticatedAppPromptDiscoveryRoute
  '/app/prompts': typeof AuthenticatedAppPromptsRoute
  '/app/report': typeof AuthenticatedAppReportRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/fiyatlandirma': typeof FiyatlandirmaRoute
  '/free-ai-readiness-report': typeof FreeAiReadinessReportRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/kvkk': typeof KvkkRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/makaleler': typeof MakalelerRouteWithChildren
  '/mcp': typeof McpRoute
  '/platform': typeof PlatformRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sunum': typeof SunumRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/makaleler/$slug': typeof MakalelerSlugRoute
  '/platform/citation-share': typeof PlatformCitationShareRoute
  '/platform/evidence-gaps': typeof PlatformEvidenceGapsRoute
  '/proof/filmfolk': typeof ProofFilmfolkRoute
  '/r/$token': typeof RTokenRoute
  '/solutions/agencies': typeof SolutionsAgenciesRoute
  '/makaleler/': typeof MakalelerIndexRoute
  '/platform/': typeof PlatformIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/app/account': typeof AuthenticatedAppAccountRoute
  '/_authenticated/app/admin': typeof AuthenticatedAppAdminRoute
  '/_authenticated/app/citation-discovery': typeof AuthenticatedAppCitationDiscoveryRoute
  '/_authenticated/app/claims': typeof AuthenticatedAppClaimsRoute
  '/_authenticated/app/content': typeof AuthenticatedAppContentRoute
  '/_authenticated/app/geo-tasks': typeof AuthenticatedAppGeoTasksRoute
  '/_authenticated/app/graph': typeof AuthenticatedAppGraphRoute
  '/_authenticated/app/integrations': typeof AuthenticatedAppIntegrationsRoute
  '/_authenticated/app/knowledge-base': typeof AuthenticatedAppKnowledgeBaseRoute
  '/_authenticated/app/measurement': typeof AuthenticatedAppMeasurementRoute
  '/_authenticated/app/onboarding': typeof AuthenticatedAppOnboardingRoute
  '/_authenticated/app/pricing': typeof AuthenticatedAppPricingRoute
  '/_authenticated/app/prompt-discovery': typeof AuthenticatedAppPromptDiscoveryRoute
  '/_authenticated/app/prompts': typeof AuthenticatedAppPromptsRoute
  '/_authenticated/app/report': typeof AuthenticatedAppReportRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/fiyatlandirma'
    | '/free-ai-readiness-report'
    | '/hakkimizda'
    | '/kvkk'
    | '/llms.txt'
    | '/makaleler'
    | '/mcp'
    | '/platform'
    | '/privacy'
    | '/sitemap.xml'
    | '/sunum'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/app'
    | '/makaleler/$slug'
    | '/platform/citation-share'
    | '/platform/evidence-gaps'
    | '/proof/filmfolk'
    | '/r/$token'
    | '/solutions/agencies'
    | '/makaleler/'
    | '/platform/'
    | '/.mcp/invoke-tool/$tool'
    | '/app/account'
    | '/app/admin'
    | '/app/citation-discovery'
    | '/app/claims'
    | '/app/content'
    | '/app/geo-tasks'
    | '/app/graph'
    | '/app/integrations'
    | '/app/knowledge-base'
    | '/app/measurement'
    | '/app/onboarding'
    | '/app/pricing'
    | '/app/prompt-discovery'
    | '/app/prompts'
    | '/app/report'
    | '/app/settings'
    | '/app/'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/fiyatlandirma'
    | '/free-ai-readiness-report'
    | '/hakkimizda'
    | '/kvkk'
    | '/llms.txt'
    | '/mcp'
    | '/privacy'
    | '/sitemap.xml'
    | '/sunum'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/makaleler/$slug'
    | '/platform/citation-share'
    | '/platform/evidence-gaps'
    | '/proof/filmfolk'
    | '/r/$token'
    | '/solutions/agencies'
    | '/makaleler'
    | '/platform'
    | '/.mcp/invoke-tool/$tool'
    | '/app/account'
    | '/app/admin'
    | '/app/citation-discovery'
    | '/app/claims'
    | '/app/content'
    | '/app/geo-tasks'
    | '/app/graph'
    | '/app/integrations'
    | '/app/knowledge-base'
    | '/app/measurement'
    | '/app/onboarding'
    | '/app/pricing'
    | '/app/prompt-discovery'
    | '/app/prompts'
    | '/app/report'
    | '/app/settings'
    | '/app'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/fiyatlandirma'
    | '/free-ai-readiness-report'
    | '/hakkimizda'
    | '/kvkk'
    | '/llms.txt'
    | '/makaleler'
    | '/mcp'
    | '/platform'
    | '/privacy'
    | '/sitemap.xml'
    | '/sunum'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/app'
    | '/makaleler/$slug'
    | '/platform/citation-share'
    | '/platform/evidence-gaps'
    | '/proof/filmfolk'
    | '/r/$token'
    | '/solutions/agencies'
    | '/makaleler/'
    | '/platform/'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/app/account'
    | '/_authenticated/app/admin'
    | '/_authenticated/app/citation-discovery'
    | '/_authenticated/app/claims'
    | '/_authenticated/app/content'
    | '/_authenticated/app/geo-tasks'
    | '/_authenticated/app/graph'
    | '/_authenticated/app/integrations'
    | '/_authenticated/app/knowledge-base'
    | '/_authenticated/app/measurement'
    | '/_authenticated/app/onboarding'
    | '/_authenticated/app/pricing'
    | '/_authenticated/app/prompt-discovery'
    | '/_authenticated/app/prompts'
    | '/_authenticated/app/report'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  FiyatlandirmaRoute: typeof FiyatlandirmaRoute
  FreeAiReadinessReportRoute: typeof FreeAiReadinessReportRoute
  HakkimizdaRoute: typeof HakkimizdaRoute
  KvkkRoute: typeof KvkkRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  MakalelerRoute: typeof MakalelerRouteWithChildren
  McpRoute: typeof McpRoute
  PlatformRoute: typeof PlatformRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SunumRoute: typeof SunumRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ProofFilmfolkRoute: typeof ProofFilmfolkRoute
  RTokenRoute: typeof RTokenRoute
  SolutionsAgenciesRoute: typeof SolutionsAgenciesRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fiyatlandirma': {
      id: '/fiyatlandirma'
      path: '/fiyatlandirma'
      fullPath: '/fiyatlandirma'
      preLoaderRoute: typeof FiyatlandirmaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-ai-readiness-report': {
      id: '/free-ai-readiness-report'
      path: '/free-ai-readiness-report'
      fullPath: '/free-ai-readiness-report'
      preLoaderRoute: typeof FreeAiReadinessReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hakkimizda': {
      id: '/hakkimizda'
      path: '/hakkimizda'
      fullPath: '/hakkimizda'
      preLoaderRoute: typeof HakkimizdaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kvkk': {
      id: '/kvkk'
      path: '/kvkk'
      fullPath: '/kvkk'
      preLoaderRoute: typeof KvkkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/makaleler': {
      id: '/makaleler'
      path: '/makaleler'
      fullPath: '/makaleler'
      preLoaderRoute: typeof MakalelerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sunum': {
      id: '/sunum'
      path: '/sunum'
      fullPath: '/sunum'
      preLoaderRoute: typeof SunumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/makaleler/': {
      id: '/makaleler/'
      path: '/'
      fullPath: '/makaleler/'
      preLoaderRoute: typeof MakalelerIndexRouteImport
      parentRoute: typeof MakalelerRoute
    }
    '/makaleler/$slug': {
      id: '/makaleler/$slug'
      path: '/$slug'
      fullPath: '/makaleler/$slug'
      preLoaderRoute: typeof MakalelerSlugRouteImport
      parentRoute: typeof MakalelerRoute
    }
    '/platform/': {
      id: '/platform/'
      path: '/'
      fullPath: '/platform/'
      preLoaderRoute: typeof PlatformIndexRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/citation-share': {
      id: '/platform/citation-share'
      path: '/citation-share'
      fullPath: '/platform/citation-share'
      preLoaderRoute: typeof PlatformCitationShareRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/evidence-gaps': {
      id: '/platform/evidence-gaps'
      path: '/evidence-gaps'
      fullPath: '/platform/evidence-gaps'
      preLoaderRoute: typeof PlatformEvidenceGapsRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/proof/filmfolk': {
      id: '/proof/filmfolk'
      path: '/proof/filmfolk'
      fullPath: '/proof/filmfolk'
      preLoaderRoute: typeof ProofFilmfolkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$token': {
      id: '/r/$token'
      path: '/r/$token'
      fullPath: '/r/$token'
      preLoaderRoute: typeof RTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/agencies': {
      id: '/solutions/agencies'
      path: '/solutions/agencies'
      fullPath: '/solutions/agencies'
      preLoaderRoute: typeof SolutionsAgenciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/account': {
      id: '/_authenticated/app/account'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AuthenticatedAppAccountRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/admin': {
      id: '/_authenticated/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AuthenticatedAppAdminRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/citation-discovery': {
      id: '/_authenticated/app/citation-discovery'
      path: '/citation-discovery'
      fullPath: '/app/citation-discovery'
      preLoaderRoute: typeof AuthenticatedAppCitationDiscoveryRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/claims': {
      id: '/_authenticated/app/claims'
      path: '/claims'
      fullPath: '/app/claims'
      preLoaderRoute: typeof AuthenticatedAppClaimsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/content': {
      id: '/_authenticated/app/content'
      path: '/content'
      fullPath: '/app/content'
      preLoaderRoute: typeof AuthenticatedAppContentRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/geo-tasks': {
      id: '/_authenticated/app/geo-tasks'
      path: '/geo-tasks'
      fullPath: '/app/geo-tasks'
      preLoaderRoute: typeof AuthenticatedAppGeoTasksRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/graph': {
      id: '/_authenticated/app/graph'
      path: '/graph'
      fullPath: '/app/graph'
      preLoaderRoute: typeof AuthenticatedAppGraphRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/integrations': {
      id: '/_authenticated/app/integrations'
      path: '/integrations'
      fullPath: '/app/integrations'
      preLoaderRoute: typeof AuthenticatedAppIntegrationsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/knowledge-base': {
      id: '/_authenticated/app/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/app/knowledge-base'
      preLoaderRoute: typeof AuthenticatedAppKnowledgeBaseRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/measurement': {
      id: '/_authenticated/app/measurement'
      path: '/measurement'
      fullPath: '/app/measurement'
      preLoaderRoute: typeof AuthenticatedAppMeasurementRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/onboarding': {
      id: '/_authenticated/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AuthenticatedAppOnboardingRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/pricing': {
      id: '/_authenticated/app/pricing'
      path: '/pricing'
      fullPath: '/app/pricing'
      preLoaderRoute: typeof AuthenticatedAppPricingRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/prompt-discovery': {
      id: '/_authenticated/app/prompt-discovery'
      path: '/prompt-discovery'
      fullPath: '/app/prompt-discovery'
      preLoaderRoute: typeof AuthenticatedAppPromptDiscoveryRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/prompts': {
      id: '/_authenticated/app/prompts'
      path: '/prompts'
      fullPath: '/app/prompts'
      preLoaderRoute: typeof AuthenticatedAppPromptsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/report': {
      id: '/_authenticated/app/report'
      path: '/report'
      fullPath: '/app/report'
      preLoaderRoute: typeof AuthenticatedAppReportRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAccountRoute: typeof AuthenticatedAppAccountRoute
  AuthenticatedAppAdminRoute: typeof AuthenticatedAppAdminRoute
  AuthenticatedAppCitationDiscoveryRoute: typeof AuthenticatedAppCitationDiscoveryRoute
  AuthenticatedAppClaimsRoute: typeof AuthenticatedAppClaimsRoute
  AuthenticatedAppContentRoute: typeof AuthenticatedAppContentRoute
  AuthenticatedAppGeoTasksRoute: typeof AuthenticatedAppGeoTasksRoute
  AuthenticatedAppGraphRoute: typeof AuthenticatedAppGraphRoute
  AuthenticatedAppIntegrationsRoute: typeof AuthenticatedAppIntegrationsRoute
  AuthenticatedAppKnowledgeBaseRoute: typeof AuthenticatedAppKnowledgeBaseRoute
  AuthenticatedAppMeasurementRoute: typeof AuthenticatedAppMeasurementRoute
  AuthenticatedAppOnboardingRoute: typeof AuthenticatedAppOnboardingRoute
  AuthenticatedAppPricingRoute: typeof AuthenticatedAppPricingRoute
  AuthenticatedAppPromptDiscoveryRoute: typeof AuthenticatedAppPromptDiscoveryRoute
  AuthenticatedAppPromptsRoute: typeof AuthenticatedAppPromptsRoute
  AuthenticatedAppReportRoute: typeof AuthenticatedAppReportRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAccountRoute: AuthenticatedAppAccountRoute,
  AuthenticatedAppAdminRoute: AuthenticatedAppAdminRoute,
  AuthenticatedAppCitationDiscoveryRoute:
    AuthenticatedAppCitationDiscoveryRoute,
  AuthenticatedAppClaimsRoute: AuthenticatedAppClaimsRoute,
  AuthenticatedAppContentRoute: AuthenticatedAppContentRoute,
  AuthenticatedAppGeoTasksRoute: AuthenticatedAppGeoTasksRoute,
  AuthenticatedAppGraphRoute: AuthenticatedAppGraphRoute,
  AuthenticatedAppIntegrationsRoute: AuthenticatedAppIntegrationsRoute,
  AuthenticatedAppKnowledgeBaseRoute: AuthenticatedAppKnowledgeBaseRoute,
  AuthenticatedAppMeasurementRoute: AuthenticatedAppMeasurementRoute,
  AuthenticatedAppOnboardingRoute: AuthenticatedAppOnboardingRoute,
  AuthenticatedAppPricingRoute: AuthenticatedAppPricingRoute,
  AuthenticatedAppPromptDiscoveryRoute: AuthenticatedAppPromptDiscoveryRoute,
  AuthenticatedAppPromptsRoute: AuthenticatedAppPromptsRoute,
  AuthenticatedAppReportRoute: AuthenticatedAppReportRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface MakalelerRouteChildren {
  MakalelerSlugRoute: typeof MakalelerSlugRoute
  MakalelerIndexRoute: typeof MakalelerIndexRoute
}

const MakalelerRouteChildren: MakalelerRouteChildren = {
  MakalelerSlugRoute: MakalelerSlugRoute,
  MakalelerIndexRoute: MakalelerIndexRoute,
}

const MakalelerRouteWithChildren = MakalelerRoute._addFileChildren(
  MakalelerRouteChildren,
)

interface PlatformRouteChildren {
  PlatformCitationShareRoute: typeof PlatformCitationShareRoute
  PlatformEvidenceGapsRoute: typeof PlatformEvidenceGapsRoute
  PlatformIndexRoute: typeof PlatformIndexRoute
}

const PlatformRouteChildren: PlatformRouteChildren = {
  PlatformCitationShareRoute: PlatformCitationShareRoute,
  PlatformEvidenceGapsRoute: PlatformEvidenceGapsRoute,
  PlatformIndexRoute: PlatformIndexRoute,
}

const PlatformRouteWithChildren = PlatformRoute._addFileChildren(
  PlatformRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  FiyatlandirmaRoute: FiyatlandirmaRoute,
  FreeAiReadinessReportRoute: FreeAiReadinessReportRoute,
  HakkimizdaRoute: HakkimizdaRoute,
  KvkkRoute: KvkkRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  MakalelerRoute: MakalelerRouteWithChildren,
  McpRoute: McpRoute,
  PlatformRoute: PlatformRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SunumRoute: SunumRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ProofFilmfolkRoute: ProofFilmfolkRoute,
  RTokenRoute: RTokenRoute,
  SolutionsAgenciesRoute: SolutionsAgenciesRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
