ALTER TABLE onecite.brand_intelligence
  ADD COLUMN IF NOT EXISTS scope text,
  ADD COLUMN IF NOT EXISTS voice_notes text,
  ADD COLUMN IF NOT EXISTS social_links jsonb NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS naming_aliases jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS naming_exclude_terms jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS alias_case_sensitive boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS content_owner_type text,
  ADD COLUMN IF NOT EXISTS review_cadence text,
  ADD COLUMN IF NOT EXISTS author_profiles jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS experience_role_type text,
  ADD COLUMN IF NOT EXISTS experience_methodologies jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS leadership jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS partnerships jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS external_recognition jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS data_sourcing_notes text,
  ADD COLUMN IF NOT EXISTS fact_checking_notes text,
  ADD COLUMN IF NOT EXISTS disclosure_policy text,
  ADD COLUMN IF NOT EXISTS content_type_focus jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS update_triggers jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS contact_points jsonb NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS default_schema_types text[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS testimonials jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS third_party_reviews jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS external_citations jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS ai_disclosure_note text;
